update_runner.update_runner_processor.*:
  type: config_entity
  label: 'Update runner processor config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    plugin:
      type: string
      label: 'plugin'
    data:
      type: sequence
      label: 'data'
    uuid:
      type: string
